### ISSUE TITLE
ldc writes to install directory

### ISSUE THREAD

**Issue by mattjhill** [ExoCTK/ExoCTKWeb#27]
The `ldc` writes to `output.txt` in the current directory where the user may not have permissions (e.g. when running on the server) causing a crash. Locations for saving files to disk should be configurable via an environment variable.

In the code I would suggest something like:
```
EXOCTK_TEMP_DIR = os.environ.get("EXOCTK_TEMP_DIR", "")
# Calculate the coefficients for each profile
grid_point = ExoCTK.ldc.ldcfit.ldc(teff, logg, feh, model_grid, profiles, 
                     mu_min=mu_min, bandpass=bandpass, plot=False, colors=COLORS,
                     save=os.path.join(EXOCTK_TEMP_DIR, 'output.txt')
```

Full traceback:
```
[2018-01-08 11:12:47,490] ERROR in app: Exception on /ldc_results [POST]
Traceback (most recent call last):
  File "/internal/data1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/internal/data1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/internal/data1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/internal/data1/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/internal/data1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/internal/data1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/internal/data1/mhill/ExoCTKWeb/exoctk_app/app_exoctk.py", line 257, in exoctk_ldc_results
    save='output.txt')
  File "/internal/data1/anaconda3/lib/python3.6/site-packages/ExoCTK-0.1.3.dev704-py3.6-linux-x86_64.egg/ExoCTK/ldc/ldcfit.py", line 285, in ldc
    with open(save, 'a') as f:
PermissionError: [Errno 13] Permission denied: 'output.txt'
```

**Comment by hover2pi** [comment]
I just removed the file writing all together (1745160).
